---
- hosts: webservers
  remote_user: ansible
  vars:
    hello: 'Welcome to Atelier Ansible'

  tasks:
    - name: Welcome
      copy:
        dest: /tmp/hello
        content: "{{ hello }}"